### PR TITLE
made average and sum aggregates ignore null values

### PR DESCRIPTION
**Pull request by Software365-info**
Number columns where a value can be null (unknown != 0) would give an error while calculating the average/sum of the column in the footer aggregate. 

This fix ignores these null values when calculating

### CODE REVIEW

**Comment by Software365-info** [comment]
Changed to draft after discovering a bug after filtering

**Comment by doonfrs** [comment]
Thank you for your collaboration.
Please let me know when it is ready.
Good luck

**Comment by doonfrs** [comment]
Merged, Thank you 🙏🙏 @Software365-info

**Comment by Software365-info** [comment]
You're welcome. Can you please provide a new build on pub.dev, containing our 2 pull requests ?
Many thanks.

**Pull request merged**
