### PR TITLE
feat: allow disable row checkbox under condition

### PR DESCRIPTION
**Pull request by yeikel16**
In some cases I need the row checkbox to be disabled to prevent user interaction. 

```dart
 PlutoColumn(
     enableColumnDrag: false,
     enableContextMenu: false,
     enableRowChecked: true,
     disableRowCheckboxWhen: (row) {
          final status = row.cells['status']?.value.toString();

          return status == '4' || status == '2';
     },
     ...
 )
```
I have tried to implement `renderer` function in `PlutoColumn` with my own checkbox, but it still shows `PlutoScaledCheckbox` widget. When I set `enableRowChecked` equal to `false`, the checkbox under the title "Checkbox All" is not available.

### CODE REVIEW

**Comment by doonfrs** [comment]
Thank you for your efforts.
Could you please remove the .fvm files and the gitignore and let's only upload the files related to the PR.
This will make it easier to review.

**Comment by muammerakilli** [comment]
PlutoColumn(
        field: 'a023',
        title: 'EKSTRA MES.',
        enableSorting: false,
        enableFilterMenuItem: false,
        enableContextMenu: false,
        enableDropToResize: false,
        type: PlutoColumnType.number(format: '#,###.##'),
        titleTextAlign: PlutoColumnTextAlign.center,
        checkReadOnly: checkReadOnly,
      )
      
  bool checkReadOnly(PlutoRow row, PlutoCell cell) {
    return row.cells['kilitle']!.value == 1;
  }
  
  
I use the checkReadOnly property to make checkboxes read-only on a cell basis. The disableRowCheckWhen property you mentioned seems to completely disable the checkboxes. Do these two methods essentially achieve the same result, or is there a significant difference between them?

**Comment by yeikel16** [comment]
> ```
>   PlutoColumn(
>         field: 'a023',
>         title: 'EKSTRA MES.',
>         enableSorting: false,
>         enableFilterMenuItem: false,
>         enableContextMenu: false,
>         enableDropToResize: false,
>         type: PlutoColumnType.number(format: '#,###.##'),
>         titleTextAlign: PlutoColumnTextAlign.center,
>         checkReadOnly: checkReadOnly,
>       )
>       
>   bool checkReadOnly(PlutoRow row, PlutoCell cell) {
>     return row.cells['kilitle']!.value == 1;
>   }
>   
> ```
> 
> I use the checkReadOnly property to make checkboxes read-only on a cell basis. The disableRowCheckWhen property you mentioned seems to completely disable the checkboxes. Do these two methods essentially achieve the same result, or is there a significant difference between them?

In my case I need show the checkbox disable("gray color and not allow interaction with it") the `checkReadOnly` method does not allow this behavior.

**Comment by yeikel16** [comment]
Hey @doonfrs, I pushed the changes !!

**Comment by doonfrs** [comment]
@yeikel16 done, thank you!

**Pull request merged**
