### PR TITLE
improve files organization

### PR DESCRIPTION
**Pull request by Macacoazul01**

### CODE REVIEW

**Comment by doonfrs** [comment]
could you please provide some description/context
Why this update is important?
What is the reason for the update ( bug, cleaner code, etc ... )?

**Comment by Macacoazul01** [comment]
Cleaner code.

There are many classes being created in that file.

Some that arent used only there.

**Comment by doonfrs** [comment]
I understand.
I don't have the chance to review it, you can merge it at your responsibility :) or wait for someone to help you review it.
Is this a break change?

**Comment by Macacoazul01** [comment]
Zero breaking changes

**Pull request merged**
