### PR TITLE
Added the ability to add a custom data property at the row level.

### PR DESCRIPTION
**Pull request by stan-at-work**
For example: you can pass data to onSelect or any other onHandler. (not required)

### CODE REVIEW

**Comment by stan-at-work** [comment]
This is a nice to have, its posible to pass data without this property. but then you needs to mingle with the key: property. And that not very integer for the code. 👍

**Comment by stan-at-work** [comment]
Its also acceptable to change the type __T__ to dynamic, but that's not verry type safe 😞

**Comment by stan-at-work** [comment]
@doonfrs any update on this?

**Comment by doonfrs** [comment]
Done, I will publish the current version to pub.dev

**Comment by stan-at-work** [comment]
Thanks

**Pull request merged**
